# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ddab8b63c548baa6df0894501a835a209772436a484c7bf0b748a9835f4dd8431c2c9f50cad175c677224bb8c5bba4d6ec14fac58daeecd53c7999603c58df6

test:
  secret_key_base: ca455fe4ab74154c7a87ac9dd0e9b3b289a55112b853ba378a63d05336ce58b06a31888d0258e0d76e72f9ebbcd72ec43f671efacfc464ed41acdeaee6419d48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
